apiVersion: v1
kind: Pod

metadata:
  name: nginx
  namespace: kube-lab

  labels:
    app: nginx-manifest
    environment: dev

  annotations:
    description: "Nginx application created by manifest"
    owner: "DevOps-Team"

spec:
  containers:
    - name: nginx
      image: nginx:1.27
