apiVersion: v1
kind: Pod

metadata:
  name: secret-env-pod
  namespace: kube-lab

spec:
  containers:
    - name: nginx
      image: nginx:1.27

      envFrom:
        - secretRef:
            name: db-secret-manifest

