apiVersion: v1
kind: Pod

metadata:
  name: secret-mount
  namespace: kube-lab

spec:
  containers:
    - name: nginx
      image: nginx

      volumeMounts:
        - name: secret-volume
          mountPath: /etc/db-secret

  volumes:
    - name: secret-volume
      secret:
        secretName: db-secret-manifest
